### ISSUE TITLE
Show pip installation instructions in docs

### ISSUE THREAD

**Issue by astrofrog** [astropy/montage-wrapper#25]

**Comment by souravsingh** [comment]
I wish to do this.Do I need to edit this doc?-https://github.com/astropy/montage-wrapper/blob/master/docs/index.rst

**Comment by astrofrog** [comment]
Yes, that would be great, thanks!

**Comment by souravsingh** [comment]
I have sent in a Pull Request for the issue-https://github.com/astropy/montage-wrapper/pull/35
