### ISSUE TITLE
Mistake in mBgExec documentation

### ISSUE THREAD

**Issue by Stargrazer82301** [astropy/montage-wrapper#34]
I just noticed what seems to be an error in the documentation for mBgExec, found at:

http://montage-wrapper.readthedocs.org/en/v0.9.5/_generated/montage_wrapper.commands.mBgExec.html#montage_wrapper.commands.mBgExec

It says that the corrections_table input parameter should be "Table of corrections generated by mFitExec"; however providing this table gives the error "Table does not contain column [id]".

The corrections_table input parameter should in fact be the table produce by mBgModel (which works for me).

Cheers!

**Comment by astrofrog** [comment]
Thanks! Fixed: https://github.com/astropy/montage-wrapper/commit/d5d6c256462fa38821e8c5340ed5e387e1812aa2
