### ISSUE TITLE
Error installing montage-wrapper having the IPAC montage software

### ISSUE THREAD

**Issue by banados** [astropy/montage-wrapper#6]
I first installed the IPAC montage software and put the bin/ folder in my $PATH. Montage is working:

```
madd
[struct stat="ERROR", msg="Usage: mAdd [-p imgdir] [-n(o-areas)] [-a mean|median|count] [-e(xact-size)] [-d level] [-s statusfile] images.tbl template.hdr out.fits"]
```

Then I tried to install montage-wrapper

```
sudo pip install montage-wrapper
```

Then I get the following error:

```
>ERROR: Montage commands could not be found.

>In order to use the montage_wrapper module, you will first need to

>install the IPAC Montage software from:

>    http://montage.ipac.caltech.edu

>and ensure that the Montage commands (e.g. mAdd, mProject, etc.) are in

>your $PATH. Your current $PATH variable contains the following paths,

>but none of them contain the Montage commands:

>   PATH = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

>If the Montage commands are in one of these directories, then please

>report this as an issue with montage-wrapper.
>----------------------------------------
>Command python setup.py egg_info failed with error code 1
>Storing complete log in /home/eduardo/.pip/pip.log
```

The thing is that IPAC is installed and if I do 

```
echo $PATH
```

My $PATH variable contains more directories than the stated by the ERROR message.
I believe the installer is not actually reading my $PATH variable but just looking in 

>  PATH = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

Is that true? how can I solve this?

**Comment by nicoywa** [comment]
Hi @astrofrog, I have the same issue, but the output of which mAdd is:

/home/nico/Programas/montage/bin/mAdd

i.e. the right path. I read all, and really I don't know what is the problem :(

**Comment by astrofrog** [comment]
I'm going to close this because I think it should be fixed in the more recent versions, but people should feel free to open a new issue if there are still issues.

**Comment by mujercohete** [comment]
I have the same problem, can someone help me, please?!!

![montage](https://user-images.githubusercontent.com/40779664/49069278-7f985400-f1ee-11e8-8ca1-f795ff4a8472.png)
